### ISSUE TITLE
非助手函数view（）,无法使用模板变量相关断言方法

### ISSUE THREAD

**Issue by cinob** [top-think/think-testing#22]
如题，只有使用return view() 这种方式才可以使用assertViewHas相关断言，正常继承controller类的渲染方式如何获取模板变量？

**Comment by yunwuxin** [comment]
返回的是 think\response\View 对象就行， 不一定是通过助手函数view

**Comment by cinob** [comment]
麻烦问一下 使用$this->visit发起的请求 如何返回think\response\View呢？

**Comment by yunwuxin** [comment]
看你的visit方法

**Comment by cinob** [comment]
visit的方法就是继承controller类 return $this->fetch(,[])这种

**Comment by yunwuxin** [comment]
最新的框架已经修正了controller里fetch的返回值

**Comment by cinob** [comment]
好的，是5.1的下个版本么？

**Comment by yunwuxin** [comment]
嗯  5.1.x-dev 里已经可以了
